transfer previous tests to  v0.0.1-misc
fostiropoulos/ablator pull request #108
Opened 2023-07-26 00:48 UTC by MrLYG

2023-07-28 22:34 UTC, fostiropoulos requested changes

2023-07-28 22:34 UTC, fostiropoulos commented on tests/utils/test_file.py
> +def test_truncate_utf8_chars_not_found():
please use tmp_path

2023-07-28 22:34 UTC, fostiropoulos commented on tests/modules/test_summary_logger.py
> +    assert l._write_config(c) is None
this is not a valid test case

2023-07-28 22:34 UTC, fostiropoulos commented on tests/modules/test_summary_logger.py
> +    assert l._make_dashboard(summary_dir=None) is None
this is not a valid test case

2023-07-28 22:34 UTC, fostiropoulos commented on tests/modules/test_optim_scheduler.py
> +    model = torch.nn.Linear(10, 1)
can we use a more complex model (you can look at `ray_models` module)?

2023-07-28 22:39 UTC, fostiropoulos commented
@Rudra-23 can you please review.

2023-08-01 21:35 UTC, Rudra-23 commented on tests/utils/test_base.py
> +    output = base.apply_lambda_to_iter(input_list, lambda x: x**2)
The function ``apply_lambda_to_iter`` takes an Iterable: which is list, dict, str and tuple. The list part is checked. However, tests on other types (especially ``dict``) can be be added.

2023-08-28 19:54 UTC, closed without merging