test cases  for progress_bar.py
fostiropoulos/ablator pull request #147
Opened 2023-09-16 01:15 UTC by VickyShel

2023-09-16 01:38 UTC, fostiropoulos requested changes
Requires several revisions.

2023-09-16 01:38 UTC, fostiropoulos commented on .idea/.gitignore
Is this file necessary?

2023-09-16 01:38 UTC, fostiropoulos commented on tests/utils/test_progress_bar.py
> +    result=get_last_line(Path("/Users/vivi/Documents/USC/实习/Ablator/ablator_v0.0.1-mp/test2.txt"))
Is this path available to all users?

2023-09-16 01:39 UTC, fostiropoulos commented
@apneetha can you please review?

2023-09-16 02:48 UTC, apneetha commented
Sure, I'll review it 

> @apneetha can you please review?

2023-09-16 08:30 UTC, apneetha commented
Hey  @VickyShel   ,  
As the one of the path for the test_get_line() is not available to all users, you could write a test case by creating a temporary file 
Instead of a passing None to the file, you could pass the an empty file.


```
def test_get_last_line(tmpdir):
    #Create a temporary file
    test_file = Path(tmpdir.join("test_file.txt"))

    # Test cases
    lines = [
        "This is the first line.",
        "Here's another line.",
        "This is the last line."
    ]
    
    with open(test_file, 'w') as f:
        f.write('\n'.join(lines))

    # Check if the function returns the expected last line
    assert get_last_line(test_file) == "This is the last line."

    # Edge case: empty file
    empty_test_file = Path(tmpdir.join("empty_test_file.txt"))
    empty_test_file.touch()  # creates an empty file
   
    try:
       result = get_last_line(empty_test_file)
    except Exception as e:
        assert False, f"Function raised an exception for an empty file: {e}"
```


```
def test_get_last_line_single_line_without_newline(tmpdir):
    # Create a temporary file
    test_file = Path(tmpdir.join("single_line_file.txt"))

    # Test case with a single line not ending with a newline
    line = "This is the only line in the file, and it doesn't end with a newline."
    
    with open(test_file, 'w') as f:
        f.write(line)

    # Check if the function returns the expected line
    assert get_last_line(test_file) == line
```

2023-09-16 08:52 UTC, apneetha commented
@VickyShel ,

For the def test_display_class(),
Could you write separate test case for each of the following, instead of having them as one file

2023-09-16 19:52 UTC, fostiropoulos requested changes

2023-09-16 19:52 UTC, fostiropoulos commented on tests/utils/test_progress_bar.py
> +    with mock.patch('ablator.utils.progress_bar.in_notebook', side_effect=ImportError):
I do not think this is a good test to see if it is robust in Notebook. The import errors could be related to other issues 
```
if "IPKernelApp" not in get_ipython().config:  # pragma: no cover
    return False
```

we should find a way to simulate that the ipykernel is running. Will require significant research.

2023-09-16 19:52 UTC, fostiropoulos commented on tests/utils/test_progress_bar.py
> +from ablator.utils.progress_bar import get_last_line
imports must be on top-level

2023-09-18 21:58 UTC, VickyShel commented on .idea/.gitignore
I will commit a new PR later. Sorry for the inconvenience.

2023-11-28 21:36 UTC, fostiropoulos commented
changes have been merged

2023-11-28 21:36 UTC, closed without merging