Merge trainers branch to examples
fostiropoulos/ablator pull request #60
Opened 2023-05-23 16:56 UTC by MrLYG

2023-05-23 17:52 UTC, fostiropoulos commented
The test are failing.

2023-05-23 17:53 UTC, fostiropoulos requested changes
The test are failing. Let's fix that before merging.

2023-05-23 19:13 UTC, fostiropoulos requested changes

2023-05-23 19:13 UTC, fostiropoulos commented on setup.py
> +        "tensorboard==2.12.2",
As we discussed, it should be removed.

2023-05-23 19:19 UTC, MrLYG commented on setup.py
> +        "tensorboard==2.12.2",
Yeah, we are working on that. and handle all TODOs

2023-05-25 17:56 UTC, fostiropoulos approved these changes

2023-05-25 17:56 UTC, merged