Add pylint and mypy check for docker runs.
fostiropoulos/ablator pull request #77
Opened 2023-06-09 22:49 UTC by MrLYG

2023-06-12 22:35 UTC, fostiropoulos commented
@MrLYG is this PR still in progress? if so can we convert to Draft?

2023-06-12 22:44 UTC, MrLYG commented
> @MrLYG is this PR still in progress? if so can we convert to Draft?

Sorry, I forgot to add a description.
This PR is finished. And It should be merged.
This PR is used to add pylint and mypy check for docker runs, on local machine.

2023-06-13 18:30 UTC, fostiropoulos requested changes

2023-06-13 18:30 UTC, fostiropoulos commented on Dockerfile
> +LABEL maintainer="dev@iordanis.xyz"
mail@iordanis.me

2023-06-14 22:58 UTC, MrLYG commented on Dockerfile
> +LABEL maintainer="dev@iordanis.xyz"
ok

2023-06-15 04:41 UTC, fostiropoulos approved these changes

2023-06-15 04:42 UTC, merged