Set threshold when codecov checks code's update.
fostiropoulos/ablator pull request #90
Opened 2023-07-03 21:48 UTC by MrLYG

2023-07-03 22:39 UTC, fostiropoulos requested changes

2023-07-03 22:39 UTC, fostiropoulos commented on codecov.yml
> +        threshold: 2.5%
can we please set to 0.5

2023-07-03 22:39 UTC, MrLYG commented on codecov.yml
> +        threshold: 2.5%
ok

2023-07-04 01:11 UTC, fostiropoulos approved these changes
Great

2023-07-04 01:11 UTC, merged