Add test for module, utils, and config
fostiropoulos/ablator pull request #94
Opened 2023-07-12 21:48 UTC by MrLYG

2023-07-13 01:04 UTC, fostiropoulos requested changes
There are missing asserts in some places. In others it is not clear whether for e.g. `math.isnan` is the expected behavior. Can you please add comment on those on the reasoning of the assert ?

2023-07-13 01:04 UTC, fostiropoulos commented on tests/modules/test_summary_logger.py
> +    dashboard.add_scalar('test_scalar', None, 1)
missing assert

2023-07-13 01:04 UTC, fostiropoulos commented on tests/utils/test_progress_bar.py
> +def test_get_last_line():
you should use `tmp_path` fixture.

2023-07-13 21:04 UTC, MrLYG commented
> In others it is not clear whether for e.g. `math.isnan` is the expected behavior

@fostiropoulos  For some functions that return None at some conditions, I want to check if that function will return None at given conditions. And also we can not use `assert value == None` when value = None in python.

So I used the `math.isnan`

2023-07-24 17:43 UTC, fostiropoulos commented
Closing this PR as the changes should be merged to `v0.0.1-mp`

2023-07-24 17:43 UTC, closed without merging